export const MONGODB_CONNECTION = process.env.MONGODB_CONNECTION;
export const GITHUB_LOGIN_CLIENT_ID = process.env.GITHUB_LOGIN_CLIENT_ID;
export const GITHUB_LOGIN_CLIENT_SECRET = process.env.GITHUB_LOGIN_CLIENT_SECRET;
export const GITHUB_LOGIN_CALLBACK_URL = process.env.GITHUB_LOGIN_CALLBACK_URL;
